language: java

jdk:
  oraclejdk11

services:
  - docker

before_install:
  - docker pull wpilib/roborio-cross-ubuntu:2019-18.04
#  - docker run -d -p 127.0.0.1:80:4567 wpilib/roborio-cross-ubuntu:2019-18.04 "ls -a; ./gradlew assemble;"
#  - docker ps -a
#  - docker run wpilib/roborio-cross-ubuntu:2019-18.04 /bin/sh -c "./gradlew check;"

script:
  - ./gradlew check

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/