!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn:
- mHandle: 0
  mName: Analog In 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiAnalogInWrapper
- mHandle: 1
  mName: Analog In 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiAnalogInWrapper
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO:
- mHandle: 0
  mName: Digital IO 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 1
  mName: Digital IO 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 2
  mName: Digital IO 2
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 3
  mName: Digital IO 3
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
mEncoders: []
mGyros: []
mPwm:
- mHandle: 0
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 1.0
  mName: Speed Controller 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 1
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 1.0
  mName: Speed Controller 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 2
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 1.0
  mName: Speed Controller 2
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 3
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 1.0
  mName: Speed Controller 3
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 105
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 1.0
  mName: CAN SC 5
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 106
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 1.0
  mName: CAN SC 6
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 107
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 1.0
  mName: CAN SC 7
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 108
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 1.0
  mName: CAN SC 8
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
mRelays:
- mHandle: 0
  mName: Relay 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiRelayWrapper
- mHandle: 1
  mName: Relay 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiRelayWrapper
mSimulatorComponents: []
mSolenoids: []
